# Generated by Django 5.0.3 on 2024-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=5, max_digits=18)),
            ],
        ),
    ]
